const test=require('node:test');const assert=require('node:assert/strict');const source=require('../src/catalog-source.js');
test('immutable review preview reads live generated catalog without freezing source URLs',()=>{const urls=source.urls({hostname:'raw.githack.com',pathname:'/chachazip-prog/kkokkapick/'+ 'a'.repeat(40)+'/index.html'},123);assert.equal(urls.catalog,'https://raw.githubusercontent.com/chachazip-prog/kkokkapick/main/data/catalog.json?ts=123');assert.ok(urls.history.endsWith('/price-history.json?ts=123'))});
test('production and local browsers keep their own generated catalog',()=>{for(const location of [{hostname:'localhost',pathname:'/'},{hostname:'chachazip-prog.github.io',pathname:'/kkokkapick/'},{hostname:'raw.githack.com',pathname:'/another/project/'},{hostname:'raw.githack.com.evil.test',pathname:'/chachazip-prog/kkokkapick/'+ 'a'.repeat(40)+'/'}])assert.equal(source.urls(location,123).catalog,'./data/catalog.json?ts=123')});
test('an explicit expiry is enforced at its boundary',()=>{assert.equal(source.isExpired({expiresAt:'2026-10-04T00:00:00Z'},Date.parse('2026-10-04T00:00:00Z')),true);assert.equal(source.isExpired({expiresAt:'2026-10-04T00:00:00Z'},Date.parse('2026-10-03T23:59:59Z')),false)});

test("malformed explicit expiry cannot silently admit stale source data",()=>{assert.equal(source.isExpired({expiresAt:"invalid"}),true)});

test("legacy TTL catalogs cannot bypass expiry by omitting expiresAt",()=>{assert.equal(source.isExpired({storagePolicy:"ttl_cache",syncedAt:"2026-10-03T00:00:00Z"},Date.parse("2026-10-04T00:00:00Z")),true);assert.equal(source.isExpired({storagePolicy:"ttl_cache"}),true)});

const previewLocation={hostname:'raw.githack.com',pathname:'/chachazip-prog/kkokkapick/'+ 'a'.repeat(40)+'/index.html'};
test('preview chooses fresher review metadata with its matching price history',async()=>{const now=Date.parse('2026-10-04T12:00:00Z');const calls=[];const result=await source.load(async url=>{calls.push(url);return new Response(JSON.stringify(url.includes('price-history')?{events:[{branch:url.includes('/codex/')}]}:{products:[],storagePolicy:'ttl_cache',syncedAt:url.includes('/codex/')?'2026-10-04T11:00:00Z':'2026-10-04T05:00:00Z'}))},previewLocation,now);assert.equal(result.catalog.syncedAt,'2026-10-04T11:00:00Z');assert.equal(result.history.events[0].branch,true);assert.equal(calls.length,3)});
test('failed review source still allows current main; both failures never silently reuse expired data',async()=>{const result=await source.load(async url=>url.includes('/codex/')?new Response('',{status:503}):new Response(JSON.stringify(url.includes('price-history')?{events:[]}:{products:[],syncedAt:'2026-10-04T05:00:00Z',storagePolicy:'ttl_cache'})),previewLocation,Date.parse('2026-10-04T12:00:00Z'));assert.equal(result.catalog.syncedAt,'2026-10-04T05:00:00Z');await assert.rejects(source.load(async()=>new Response('',{status:503}),previewLocation),/Catalog fetch failed/)});
test('expired source does not fetch history or pretend it is fresh',async()=>{let calls=0;const result=await source.load(async()=>{calls++;return new Response(JSON.stringify({products:[],storagePolicy:'ttl_cache',syncedAt:'2026-10-03T00:00:00Z'}))},{hostname:'localhost'},Date.parse('2026-10-04T12:00:00Z'));assert.equal(source.isExpired(result.catalog,Date.parse('2026-10-04T12:00:00Z')),true);assert.equal(result.history,null);assert.equal(calls,1)});
