const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('src/release-ui.js','utf8');
const escape=source.slice(source.indexOf('function esc('),source.indexOf('function won('));
const names=source.slice(source.indexOf('function displayName('),source.indexOf('function imageHtml('));
const information=source.slice(source.indexOf('function materialLabel('),source.indexOf('function readStore('));
const engine=source.slice(source.indexOf('const VERIFIED_SIZE_CHARTS='),source.indexOf('function positivePrice('));
const context=vm.createContext({});vm.runInContext(escape+names+information+engine,context);
const original={brand:'아가방',name:'아가방 아양우주복(모자)(O/WHITE)_01R71750503'};
assert.equal(context.displayName(original),'아양 우주복 + 모자 세트');assert.equal(original.name,'아가방 아양우주복(모자)(O/WHITE)_01R71750503','source preserved');
assert.equal(context.displayName({brand:'아가방',name:'[이마트몰] 아가방 아가방 봄 원피스 (52935592)'}),'봄 원피스');
assert.equal(context.displayName({name:'키즈 코튼 티셔츠 2종 세트'}),'키즈 코튼 티셔츠 2종 세트','meaningful quantity preserved');
assert.equal(context.materialLabel({materials:['면 95%','폴리에스터 5%']}),'면 95%, 폴리에스터 5%');
assert.equal(context.sizeLabel({availableSizes:['80','90','100']}),'80, 90, 100');
const absent=context.productInfoHtml({cat:'바디수트',availableSizes:[]});assert.ok(absent.includes('소재'));assert.ok(absent.includes('판매처 상세페이지 확인'));assert.ok(absent.includes('사이즈'));assert.ok(absent.includes('판매처 옵션 및 실측 확인'));assert.ok(!absent.includes('면 100%'),'do not invent material');
assert.ok(context.productInfoHtml({material:'<img onerror=alert(1)>',availableSizes:[]}).includes('&lt;img'));
assert.equal(context.evaluateFit({months:0,height:50,weight:4},{brand:'아가방'}).status,'recommended','newborn age 0 is valid');
console.log('Release presentation: source-preserving names, truthful material/size and zero-month fit PASS');
