import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const script=path.resolve('scripts/handoff-review-catalog.cjs');
test('handoff refuses main and non-manual events before touching data',()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'kk-handoff-'));try{for(const [ref,event] of [['refs/heads/main','workflow_dispatch'],['refs/heads/codex/release-ui-rebuild','pull_request']]){const p=spawnSync(process.execPath,[script],{cwd,env:{...process.env,GITHUB_REPOSITORY:'chachazip-prog/kkokkapick',GITHUB_REF:ref,GITHUB_EVENT_NAME:event},encoding:'utf8'});assert.notEqual(p.status,0);assert.ok(!fs.existsSync(path.join(cwd,'data')));assert.match(p.stderr,/Only the review branch|Manual handoff only/)}}finally{fs.rmSync(cwd,{recursive:true,force:true})}});
test('an expired artifact is rejected without replacing any current data',()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'kk-handoff-'));try{fs.mkdirSync(path.join(cwd,'.review-catalog'));fs.mkdirSync(path.join(cwd,'data'));fs.writeFileSync(path.join(cwd,'data/catalog.json'),'original');for(const [name,data] of Object.entries({'catalog.json':{products:Array.from({length:250},()=>({})),productCount:250,sourceCount:0,expiresAt:'2000-01-01T00:00:00Z'},'adpick-biz-products.json':{products:[],count:0},'price-history.json':{events:[]}}))fs.writeFileSync(path.join(cwd,'.review-catalog',name),JSON.stringify(data));const p=spawnSync(process.execPath,[script],{cwd,env:{...process.env,GITHUB_REPOSITORY:'chachazip-prog/kkokkapick',GITHUB_REF:'refs/heads/codex/release-ui-rebuild',GITHUB_EVENT_NAME:'workflow_dispatch'},encoding:'utf8'});assert.notEqual(p.status,0);assert.match(p.stderr,/Expired review catalog/);assert.equal(fs.readFileSync(path.join(cwd,'data/catalog.json'),'utf8'),'original')}finally{fs.rmSync(cwd,{recursive:true,force:true})}});

import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {validateRun}=require('../scripts/validate-review-artifact-run.cjs');
test('artifact provenance rejects other workflows, events, branches and failed runs',()=>{const valid={repository:{full_name:'chachazip-prog/kkokkapick'},head_repository:{full_name:'chachazip-prog/kkokkapick'},path:'.github/workflows/adpick-image-diagnostic.yml',event:'workflow_dispatch',head_branch:'codex/release-ui-rebuild',status:'completed',conclusion:'success'};assert.doesNotThrow(()=>validateRun(valid));for(const overrides of [{path:'.github/workflows/unrelated.yml'},{event:'pull_request'},{head_branch:'main'},{conclusion:'failure'},{head_repository:{full_name:'someone/fork'}}])assert.throws(()=>validateRun({...valid,...overrides}))});

test('handoff cannot extend retention with a distant future expiry',()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'kk-handoff-'));try{fs.mkdirSync(path.join(cwd,'.review-catalog'));fs.mkdirSync(path.join(cwd,'data'));fs.writeFileSync(path.join(cwd,'data/catalog.json'),'original');const syncedAt=new Date().toISOString(),expiresAt='2099-01-01T00:00:00Z';const products=Array.from({length:250},()=>({}));for(const [name,data] of Object.entries({'catalog.json':{products,productCount:250,sourceCount:250,storagePolicy:'ttl_cache',syncedAt,expiresAt},'adpick-biz-products.json':{products,count:250,storagePolicy:'ttl_cache',syncedAt,expiresAt,imageHealth:{rate:1}},'price-history.json':{events:[]}}))fs.writeFileSync(path.join(cwd,'.review-catalog',name),JSON.stringify(data));const p=spawnSync(process.execPath,[script],{cwd,env:{...process.env,GITHUB_REPOSITORY:'chachazip-prog/kkokkapick',GITHUB_REF:'refs/heads/codex/release-ui-rebuild',GITHUB_EVENT_NAME:'workflow_dispatch'},encoding:'utf8'});assert.notEqual(p.status,0);assert.match(p.stderr,/TTL must not exceed 24 hours/);assert.equal(fs.readFileSync(path.join(cwd,'data/catalog.json'),'utf8'),'original')}finally{fs.rmSync(cwd,{recursive:true,force:true})}});

test('unexpired metadata cannot publish review images beyond the display window',()=>{
 const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'kk-handoff-'));
 try{
  fs.mkdirSync(path.join(cwd,'.review-catalog'));fs.mkdirSync(path.join(cwd,'data'));
  const baseline={syncedAt:'2000-01-01T00:00:00Z',products:Array.from({length:250},()=>({}))};
  fs.writeFileSync(path.join(cwd,'data/catalog.json'),JSON.stringify(baseline));
  const fixtureNow=Date.now();const syncedAt=new Date(fixtureNow-2*3600000).toISOString(),expiresAt=new Date(fixtureNow+22*3600000).toISOString(),products=Array.from({length:250},()=>({}));
  for(const [name,data] of Object.entries({'catalog.json':{products,productCount:250,sourceCount:250,storagePolicy:'ttl_cache',syncedAt,expiresAt},'adpick-biz-products.json':{products,count:250,storagePolicy:'ttl_cache',syncedAt,expiresAt,imageHealth:{rate:1}},'price-history.json':{events:[]}}))fs.writeFileSync(path.join(cwd,'.review-catalog',name),JSON.stringify(data));
  const result=spawnSync(process.execPath,[script],{cwd,env:{...process.env,GITHUB_REPOSITORY:'chachazip-prog/kkokkapick',GITHUB_REF:'refs/heads/codex/release-ui-rebuild',GITHUB_EVENT_NAME:'workflow_dispatch'},encoding:'utf8'});
  assert.notEqual(result.status,0);assert.match(result.stderr,/display window/);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(cwd,'data/catalog.json'))),baseline);
 }finally{fs.rmSync(cwd,{recursive:true,force:true})}
});
