const cfg=window.KKOKKAPICK_ADMIN_CONFIG||{};
const state={session:null,campaigns:[],partners:[],popups:[],selectedProducts:[]};
const $=s=>document.querySelector(s);
const status=$('#connectionStatus'), save=$('#saveCampaign'), savePopup=$('#savePopup');
function configured(){return Boolean(cfg.enabled&&cfg.supabaseUrl&&cfg.supabaseAnonKey)}
function headers(extra={}){return {'apikey':cfg.supabaseAnonKey,'Authorization':'Bearer '+(state.session?.access_token||cfg.supabaseAnonKey),'Content-Type':'application/json',...extra}}
async function api(path,options={}){const r=await fetch(cfg.supabaseUrl+'/rest/v1/'+path,{...options,headers:headers(options.headers)});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function loadCampaigns(){if(!configured()||!state.session)return;state.partners=await api('commercial_partners?select=id,name,partner_type,status&order=name');state.campaigns=await api('commercial_campaigns?select=id,title,campaign_type,status,starts_at,ends_at,placement,priority&order=created_at.desc');state.popups=await api('managed_popups?select=id,title,status,surface,dismiss_policy,starts_at,ends_at,priority&order=created_at.desc');render()}
function render(){const box=$('#campaignRows');if(box)box.innerHTML=state.campaigns.length?state.campaigns.map(c=>`<div class="row"><b>${escapeHtml(c.title)}</b><span class="badge">${escapeHtml(c.status)}</span><span>${escapeHtml(c.campaign_type)}</span><span><button class="tab" data-campaign-action="${c.id}:published">게시</button><button class="tab" data-campaign-action="${c.id}:paused">중지</button><button class="tab" data-campaign-copy="${c.id}">복제</button></span></div>`).join(''):'<div class="row"><b>등록된 캠페인이 없습니다.</b><span class="badge">—</span><span>—</span><span>—</span></div>';const partner=$('#campaignPartner');if(partner)partner.innerHTML='<option value="">파트너 선택</option>'+state.partners.map(x=>`<option value="${escapeHtml(x.id)}">${escapeHtml(x.name)}</option>`).join('');const p=$('#popupRows');if(p)p.innerHTML=(state.popups||[]).length?state.popups.map(x=>`<div class="row"><b>${escapeHtml(x.title)}</b><span class="badge">${escapeHtml(x.status)}</span><span>${escapeHtml(x.surface)}</span><span><button class="tab" data-popup-action="${x.id}:published">게시</button><button class="tab" data-popup-action="${x.id}:paused">중지</button></span></div>`).join(''):'<div class="row"><b>등록된 팝업이 없습니다.</b><span class="badge">—</span><span>전체</span><span>—</span></div>'}
function toIso(v){return v?new Date(v).toISOString():null}
function renderSelected(){const b=$('#selectedProducts');if(b)b.innerHTML=state.selectedProducts.length?state.selectedProducts.map((p,i)=>`<span class="badge" style="margin:2px">${i+1}. ${escapeHtml(p.name)} <button type="button" data-remove-product="${escapeHtml(p.id)}">×</button></span>`).join(''):'선택 상품 없음'}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function signIn(email,password){const r=await fetch(cfg.supabaseUrl+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('로그인에 실패했습니다.');state.session=await r.json();await loadCampaigns()}
async function saveDraft(){
 const payload={title:$('#campaignTitle').value.trim(),partner_id:$('#campaignPartner').value||null,campaign_type:$('#campaignType').value,status:'draft',disclosure_label:'Sponsored',placement:$('#placement').value||null,starts_at:toIso($('#campaignStart').value),ends_at:toIso($('#campaignEnd').value)};
 if(!payload.title)return alert('캠페인명을 입력하세요.');
 const created=await api('commercial_campaigns',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});const id=created?.[0]?.id;if(id&&state.selectedProducts.length)await api('commercial_campaign_products',{method:'POST',body:JSON.stringify(state.selectedProducts.map((p,i)=>({campaign_id:id,product_id:p.id,sort_order:i})))});state.selectedProducts=[];renderSelected();await loadCampaigns();
}
$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await signIn($('#adminEmail').value,$('#adminPassword').value);status.textContent='관리자 연결됨';save.disabled=false;if(savePopup)savePopup.disabled=false;const ev=$('#saveEvidence');if(ev)ev.disabled=false;$('#loginPanel').hidden=true}catch(err){alert(err.message)}});
$('#quickPartner')?.addEventListener('click',async()=>{if(!configured()||!state.session)return alert('관리자 로그인 후 사용할 수 있습니다.');const name=prompt('새 파트너/브랜드명');if(!name?.trim())return;try{await api('commercial_partners',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:name.trim(),partner_type:'sponsor',status:'draft'})});await loadCampaigns()}catch(e){alert('파트너 추가 실패: '+e.message)}});
$('#previewPopup')?.addEventListener('click',()=>{const box=$('#popupPreview');$('#popupPreviewTitle').textContent=$('#popupTitle').value.trim()||'팝업 제목';box.hidden=!box.hidden});
$('#saveEvidence')?.addEventListener('click',async()=>{try{const brand=$('#evidenceBrand').value.trim(),url=$('#evidenceUrl').value.trim();if(!brand)return alert('브랜드를 입력하세요.');if(url&&!/^https?:\/\//i.test(url))return alert('공식 출처는 http/https 주소를 입력하세요.');await api('brand_size_evidence',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({brand,status:$('#evidenceStatus').value,source_url:url||null,evidence_note:$('#evidenceNote').value.trim()||null,verified_at:$('#evidenceStatus').value==='verified'?new Date().toISOString():null})});alert('근거가 저장되었습니다.')}catch(e){alert('근거 저장 실패: '+e.message)}});
let searchTimer;$('#catalogSearch')?.addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchCatalog(e.target.value),300)});
async function searchCatalog(q){const box=$('#catalogResults');if(!configured()||!state.session||q.trim().length<2){box.innerHTML='<p style="font-size:12px;color:#777">2글자 이상 입력하세요.</p>';return}try{const safe=encodeURIComponent('*'+q.trim()+'*');const rows=await api('products?select=id,name,brand,category,stage&name=ilike.'+safe+'&limit=20');box.innerHTML=rows.length?rows.map(x=>`<div class="row"><b>${escapeHtml(x.name)}</b><span>${escapeHtml(x.brand||'미분류')}</span><span>${escapeHtml(x.category||'')}</span><button class="btn secondary" type="button" data-hide="${escapeHtml(x.id)}">숨김</button></div>`).join(''):'<p>검색 결과 없음</p>'}catch(e){box.textContent='검색 실패: '+e.message}}
$('#catalogResults')?.addEventListener('click',async e=>{const id=e.target?.dataset?.hide;if(!id)return;if(!confirm('이 상품을 숨길까요?'))return;try{await api('catalog_overrides',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({product_id:id,hidden:true,note:'admin hide'})});e.target.textContent='숨김됨';e.target.disabled=true}catch(err){alert('처리 실패: '+err.message)}});
save?.addEventListener('click',()=>saveDraft().catch(e=>alert('저장 실패: '+e.message)));
savePopup?.addEventListener('click',async()=>{try{const title=$('#popupTitle').value.trim();if(!title)return alert('팝업 제목을 입력하세요.');const url=$('#popupUrl').value.trim();if(url&&!/^https?:\/\//i.test(url))return alert('링크는 http/https 주소만 입력하세요.');await api('managed_popups',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({title,status:'draft',surface:$('#popupSurface').value,dismiss_policy:$('#popupDismiss').value,destination_url:url||null,starts_at:toIso($('#popupStart').value),ends_at:toIso($('#popupEnd').value)})});await loadCampaigns()}catch(e){alert('팝업 저장 실패: '+e.message)}});
if(configured()){status.textContent='Supabase 연결 준비됨 · 관리자 로그인 필요';}else{status.textContent='안전 모드 · Supabase 설정 전에는 조회/저장이 비활성화됩니다.';}

let cpsTimer;$('#campaignProductSearch')?.addEventListener('input',e=>{clearTimeout(cpsTimer);cpsTimer=setTimeout(()=>searchCampaignProducts(e.target.value),250)});
async function searchCampaignProducts(q){const box=$('#campaignProductResults');if(!box||q.trim().length<2){if(box)box.innerHTML='';return}try{const safe=encodeURIComponent('*'+q.trim()+'*');const rows=await api('products?select=id,name,brand&name=ilike.'+safe+'&limit=12');box.innerHTML=rows.map(x=>`<button class="tab" type="button" data-add-product="${escapeHtml(x.id)}" data-product-name="${escapeHtml(x.name)}">${escapeHtml(x.name)}</button>`).join('')}catch(e){box.textContent='검색 실패'}}
$('#campaignProductResults')?.addEventListener('click',e=>{const id=e.target?.dataset?.addProduct;if(!id)return;if(!state.selectedProducts.some(x=>x.id===id))state.selectedProducts.push({id,name:e.target.dataset.productName});renderSelected()});
$('#selectedProducts')?.addEventListener('click',e=>{const id=e.target?.dataset?.removeProduct;if(!id)return;state.selectedProducts=state.selectedProducts.filter(x=>x.id!==id);renderSelected()});

async function rpc(name,body){if(!configured()||!state.session)throw new Error('관리자 로그인이 필요합니다.');const r=await fetch(cfg.supabaseUrl+'/rest/v1/rpc/'+name,{method:'POST',headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
$('#campaignRows')?.addEventListener('click',async e=>{try{if(e.target.dataset.campaignAction){const [id,status]=e.target.dataset.campaignAction.split(':');await rpc('admin_set_campaign_status',{p_id:id,p_status:status});await loadCampaigns()}else if(e.target.dataset.campaignCopy){await rpc('admin_duplicate_campaign',{p_id:e.target.dataset.campaignCopy});await loadCampaigns()}}catch(err){alert('캠페인 처리 실패: '+err.message)}});
$('#popupRows')?.addEventListener('click',async e=>{if(!e.target.dataset.popupAction)return;try{const [id,status]=e.target.dataset.popupAction.split(':');await rpc('admin_set_popup_status',{p_id:id,p_status:status});await loadCampaigns()}catch(err){alert('팝업 처리 실패: '+err.message)}});
